### PR TITLE
F/A-18C Interface Fixes

### PR DESCRIPTION
**Pull request by MedievalBunny**
DCS F/A-18C:
Added ASPJ Mode Dial
Fixed Left and Right DDI Brightness Selector Knob
Fixed Dispenser Switch
Fixed Launch Bar Switch
Fixed Cockpit Lights Mode Switch 
Fixed Strobe Lights Switch
Fixed Refuel Probe Switch

DCS F-16C:
Added ECM Panel buttons
Fixed all MFD rocker switches
Fixed DCS / Dobber switch

DCS AH-64D:
Created new Interface for the Apache

I've never submitted any code to Github before, I don't know what I'm doing.

### CODE REVIEW

**Comment by Todd1215** [comment]
reviewing

**Comment by derammo** [comment]
> I've never submitted any code to Github before, I don't know what I'm doing.

Doing great so far :)

**Comment by BlueFinBima** [comment]
@MedievalBunny Alex,  great job!  I really appreciate you taking the time & effort to improve Helios.  

I've taken your Hornet changes and mirrored them to the C# interface https://github.com/HeliosVirtualCockpit/Helios/commit/0cb4f5166fb5e2d49270c1e8666df2c865ad0ecc which generated the JSON you corrected.  I'll regenerate the JSON for that interface from the Helios Profile Editor.

Helios will shortly have an AH-64D interface in C#.  This provides a little challenge to reconcile your JSON with the JSON for the C# interface (style 1).  The style 1 interface was missing two switches (319 and 363) which have been added by https://github.com/HeliosVirtualCockpit/Helios/commit/7608be9f799256d014653f7441442554aa4e0bdf

The biggest change between the two JSON interfaces is the interface names for the functions.  If you already have an Apache profile, then this will not work with the style 1 interface.  This said, I'd be interested in seeing an Apache Profile if you have one and potentially changing the bindings to fit with the style 1 interface.    

I did a reconciliation on the two JSON Apache interfaces, and the JSON generated from the style 1 interface is a superset of the one in this PR.   For reference, the missing IDs are 310, 311, 312, 313, 319, 320, 321, 322, 323, 324, 325, 353, 354, 355, 358, 359, 360, 361, 368, 369, 370, 371, 372, 373, 374, 397, 403, 404, 405, 407, 408, 409, 410, 411, 412, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 477, 619, 620, 622, 623, 624, 625, 626, 627, 634, 636, 801, 802, 803, 804 .  I have made no attempt to validate that the functionality of the two JSON interfaces are the same.  It is certainly possible that the one generated from the style 1 interface might contain bugs fixed in your JSON interface,

**Comment by derammo** [comment]
@MedievalBunny if you don't know what "Style 1 interface" means, that's because this is something I only defined last Friday. :)

Here are the definitions: https://github.com/HeliosVirtualCockpit/Helios/wiki/Developing-DCS-Interfaces

**Comment by MedievalBunny** [comment]
@derammo Interesting, only about half of that makes sense to me - I'm no programmer, I'm just good at poking things until they work :P

Is there a preferred Style for Interfaces moving forward? Most of them seem to currently be Style 2, but the Apache will be Style 1?

@BlueFinBima 

> the JSON generated from the style 1 interface is a superset of the one in this PR.

That makes sense. I wrote the JSON by hand addressing only the functions I wanted for my profile, and did not include every function in the pit. Everything in my JSON is confirmed working on my end, if that simplifies any troubleshooting or conflict resolution.

I've got a working profile in use by the community [here.](https://forum.dcs.world/topic/286561-apache-profile-using-helios-for-a-second-monitor/?do=findComment&comment=4957141) But I'm also happy to change bindings in the profile if needed, it's not that hard.

**Comment by derammo** [comment]
> 
> Is there a preferred Style for Interfaces moving forward? Most of them seem to currently be Style 2, but the Apache will be Style 1?
> 

If your interface doesn't need any special UI (i.e. it can just use the generic DCS Interface UI,) then Style 3 is the best.  That way, there is no code.   If you need a C# class so you can add some special stuff or a special UI, then you just use the same JSON for a Style 2 interface.   

Right now there is only one Style 2 interface (F/A-18C) because that's what I prototyped with.   

All the existing C# interfaces predate my JSON work and are Style 1.

The Apache interface that BlueFinBima is creating is starting its life as Style 1, because that is what he is comfortable with.  I assume it will then get exported to Style 2 so people can do fixes in the field.

If I was this active on this project, I would replace all Style 1 interfaces with Style 2, because that was what I was working on.  Helios automatically writes the JSON for you from the C# code, so there isn't any good reason not to switch everything over.  There is existing code that knows about the C# classes, so that's why they have to stay a Style 2 (C# class with all its guts replaced with a JSON file) instead of becoming a pure JSON Style 3 interface.

**Pull request closed without merging**
