### PR TITLE
Update F-14 Device Id

### PR DESCRIPTION
**Pull request by MedievalBunny**
Updated a number of incorrect F-14 Device Ids, and updated some switch position names while I was at it.

### CODE REVIEW

**Comment by BlueFinBima** [comment]
@MedievalBunny Hi Alex, Firstly many thanks for the PR.  I don't have the ability to test / verify the F-14 changes at this time.  Can you please confirm that you have tested all these changes.  Thanks

**Comment by MedievalBunny** [comment]
@BlueFinBima I've tested most, but not all, of the pilot-side changes. I have not tested any of the RIO-side changes.

**Comment by MedievalBunny** [comment]
@BlueFinBima Tested all functions with one exception: a number of RIO ECMD controls in Helios don't seem to be for anything in the F-14 pit, they look to be there for the currently non-existent ALR-45. 

I also found an unrelated error with the RIO Airspeed Indicator. I've fixed it on my fork, I'm not sure if that'll get pulled into this PR or if I need to make a new one for that.

**Comment by BlueFinBima** [comment]
@MedievalBunny Alex, was the inclusion of the Apache switch 154 [6602f81](https://github.com/HeliosVirtualCockpit/HeliosInterfaces/pull/8/commits/6602f81a40d9c16ba41927c94b16ce332d579569) intentional?  It seems to regress the current level of the Apache.

**Comment by BlueFinBima** [comment]
F-14 Interface changes pulled from @MedievalBunny 's fork and committed as https://github.com/HeliosVirtualCockpit/HeliosInterfaces/commit/b4c4eaee604a294d13c7529e87024690b32c6f87

**Comment by MedievalBunny** [comment]
@BlueFinBima No, the Apache inclusion is unintentional. I'm not sure why it was included at all, nor can I figure out how to make it go away.

**Comment by BlueFinBima** [comment]
Since this PR was achieved by merging in directly from MedievalBunny's fork, I'm closing this PR.

**Pull request closed without merging**
